window.host = {}, host.uikit = "d1qgs0cj2a6pkw.cloudfront.net/moprosuite/v255/uikit/_static";
            host.builder = "create2.mopro.com";
            host.builderstatic = "d1qgs0cj2a6pkw.cloudfront.net/moprosuite/v255/create/_static";
            host.wo = {}, host.wo.web = "create2.mopro.com", host.wo.static = "d1qgs0cj2a6pkw.cloudfront.net/moprosuite/v255/create/_static2";
            host.administration = {}, host.administration.web = "administration2.mopro.com", host.administration.static = "d1qgs0cj2a6pkw.cloudfront.net/moprosuite/v255/administration/_static";
            host.old_builder = {}, host.old_builder.web = "website2.mopro.com", host.old_builder.static = "d1qgs0cj2a6pkw.cloudfront.net/moprosuite/v255/website/_static";
            host.checkout = {}, host.checkout.web = "selfcheckout.mopro.com", host.checkout.static = "d17my9ypnvqzep.cloudfront.net/moprosystems/selfcheckout/v2/_static";
            host.smartbooker = "https://smartbooker.mopro.com";
            host.pulse = {}, host.pulse.web = "pulse.mopro.com", host.pulse.static = "pulse.mopro.com/_static";
            window.apiKey = {}, apiKey.Google = "AIzaSyDOQ5A3f4cAp7goKc2no9hAXlH4e_03ctQ", apiKey.Bitly = "R_4c53b91f0d53463ea20757d5d78fa0b5", apiKey.Recaptcha = "6LenKOYSAAAAAE22MAJulHs1_80BzCIsQS18Y9ey", apiKey.Segment = "N3lCJIJMfuUmGIgrRHxoVxDxp6rBglT2";
            apiKey.IPInfo = "d4b1c52d60777c";
            window.cred = {}, cred.bitly = "mobit4";
            window.url = {}, url.getService = {}, url.getService.administration = "https://administrationapi2.mopro.com/Administration.svc";
            url.getService.appsetting = "https://appsettingapi2.mopro.com/AppSetting.svc";
            url.getService.checkout = "https://checkoutapi.mopro.com/Checkout.svc";
            url.getService.dashboard = "https://contentdelieveryapi2.mopro.com/ContentDelivery.svc";
            url.getService.builder = "https://builderapi2.mopro.com/Builder.svc";
            url.getService.websiteoutput = "https://websiteoutputapi2.mopro.com/WebsiteOutput.svc";
            url.setService = "https://coreapi2.mopro.com/Core.svc";
            url.bitly = "https://api-ssl.bitly.com/v3/shorten";
            url.api = {}, url.api.ecommerce = "https://ecommerceapi2.mopro.com/api/v1";
            url.api.oauth = "https://oauthapi2.mopro.com/api";
            url.api.rewards = "https://rewardapi2.mopro.com/api/v1";
            url.api.idx = "https://idxapi2.mopro.com/api/v1";
            url.api.socialpublisher = "https://socialapi2.mopro.com/api/v1";
            url.api.revisionintake = "https://pulseapi.mopro.com/api/v1";
            window.app = {}, app.lang = "en_US";
            window.CacheKey = "v255";
            window.config = {};
            config.ProjectID = "aa784541-7f5e-4189-8e74-7a03b9d75971";
            config.SiteID = "26db6091-4efa-40aa-b5e3-7e8fd4e939a7";
            config.IsPublish = "1";
            config.Domain = "www.destinique.com";